<html>
    <body>
        <form method="GET" action="#" >
            <input type="number" placeholder="var1" name="num1">
            <input type="number" placeholder="var2" name="num2">
            <br>
            <input type="number" placeholder="var3" name="num3">
            <input type="number" placeholder="var4" name="num4">

            <input type="submit">

        </form>

        <?php 
            $num1 = $_GET["num1"];
           
            $num2 = $_GET["num2"];
            
            $num3 = $_GET["num3"];
            
            $num4 = $_GET["num4"];
           

            maiornumero($num1, $num2);
                maiornumero($num3, $num4);
           
            function maiornumero($n1, $n2) {
                if($n1> $n2){
                    echo "esse é o maior valor " . $n1 . "<br>";
                }else{
                    echo "esse é o maior " . $n2 . "<br>";
                }
            }

        ?>
    </body>
</html>